require("woniulol.plugins.lsp_config.lua_ls")
require("woniulol.plugins.lsp_config.ty")
require("woniulol.plugins.lsp_config.pyright")
require("woniulol.plugins.lsp_config.basedpyright")
require("woniulol.plugins.lsp_config.rust_analyzer")
